### PR TITLE
Shorten Compare URLs

### LINKED ISSUE #16: Inaccurate compare links
## Input
`https://github.com/BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec` [🔗](https://github.com/BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec)
`https://github.com/BrowserSync/browser-sync/compare/client-ts` [🔗](https://github.com/BrowserSync/browser-sync/compare/client-ts)
`https://github.com/BrowserSync/browser-sync/compare/client-ts...master`  [🔗](https://github.com/BrowserSync/browser-sync/compare/client-ts...master)

## Output
BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec
BrowserSync/browser-sync/compare/client-ts
BrowserSync/browser-sync@`client-ts...master`

## Expected
BrowserSync/browser-sync@`62007c8` (compare)
BrowserSync/browser-sync@`client-ts` (compare)
BrowserSync/browser-sync@`client-ts...master` (compare)

### PR DESCRIPTION
**Pull request by jerone**
# Description
This will detect compare urls.

## Input
`https://github.com/bfred-it/shorten-repo-url/compare`
`https://github.com/bfred-it/shorten-repo-url/compare/d71718db6aa4feb8dc10edbad1134472468e971a`
`https://github.com/bfred-it/shorten-repo-url/compare/master`
`https://github.com/bfred-it/shorten-repo-url/compare/master...master`

## Output
bfred-it/shorten-repo-url/compare
bfred-it/shorten-repo-url@`d71718d` (compare)
bfred-it/shorten-repo-url@`master` (compare)
bfred-it/shorten-repo-url@`master...master` (compare)

# Closes
 #16

### CODE REVIEW

**Comment by jerone** [comment]
Failing CI build with Node 7 [seems unrelated](https://travis-ci.org/bfred-it/shorten-repo-url/jobs/540187255#L1224-L1237) to this PR.

**Comment by bfred-it** [comment]
Can you replace the 7 with 8? It's annoying that they increased the compatibility breaking semver, but this change only affects the build anyway.

**Comment by jerone** [comment]
Increased minimum Nodejs version to 8. All tests pass again.

**Comment by bfred-it** [comment]
Thanks! I think the engines field can stay as is, I won't make any changes that break Node 7 compatibility in the published module. v8 is only needed on Travis because of that devDependency requiring it

**Pull request merged**
